# Generated by Django 4.2 on 2023-04-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_group_remove_workout_date_customuser_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='intervalVariableType',
            field=models.CharField(blank=True, choices=[('Int_distance', 'Interval Distance'), ('Int_time', 'Interval Time'), ('Int_var', 'Intervals variable')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='split_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='workoutTime',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='workoutType',
            field=models.CharField(blank=True, choices=[('AT', 'AT'), ('SS', 'SS'), ('Race_pace', 'Race pace')], max_length=20, null=True),
        ),
    ]
