# Generated by Django 4.1.7 on 2023-04-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_workout_id'),
        ('app', '0002_group_remove_workout_date_customuser_organization_and_more'),
    ]

    operations = [
    ]
