# Generated by Django 4.1.7 on 2023-04-23 00:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workout_date_workout_intervalvariabletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('pr_length_minutes', models.IntegerField(blank=True, default=1, null=True)),
                ('pr_length_sec', models.IntegerField(blank=True, default=1, null=True)),
                ('lastWorkout', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('goal_length_minutes', models.IntegerField(blank=True, default=1, null=True)),
                ('goal_length_sec', models.IntegerField(blank=True, default=1, null=True)),
                ('injured', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='AM', max_length=20, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='intervalVariableType',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='type',
        ),
        migrations.AddField(
            model_name='workout',
            name='rowingType',
            field=models.CharField(blank=True, choices=[('single_distance', 'Single Distance'), ('single_time', 'Single Time'), ('Int_distance', 'Interval Distance'), ('Int_time', 'Interval Time'), ('Int_var', 'Intervals variable')], default='single_distance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='distanceInt',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='distance_meters',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='int_time_minutes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='int_time_sec',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='member_count',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='num_intervals',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='rest_time_minutes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='rest_time_sec',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='split_length',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='split_length_minutes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='split_length_seconds',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_minutes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time_seconds',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workoutTime',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workoutType',
            field=models.CharField(blank=True, choices=[('AT', 'AT'), ('SS', 'SS'), ('Race_pace', 'Race pace')], default='SS', max_length=20, null=True),
        ),
    ]
