# Generated by Django 4.1.7 on 2023-04-02 21:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20230402_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
